apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
  labels:
    app: php-webserver
spec:
  replicas: 4
  selector:
    matchLabels:
      app: php-webserver
  template:
    metadata:
      labels:
        app: php-webserver
    spec:
      containers:
      - name: phpdemo
        image: pulsemanchaotix/phpdemo
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
spec:
  selector:
    app: php-webserver
  type: LoadBalancer
  loadBalancerIP: 192.168.100.162
  ports:
  - name: http
    port: 8888
    targetPort: 80
    protocol: TCP