apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
  labels:
    app: php-webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-webserver
  template:
    metadata:
      labels:
        app: php-webserver
    spec:
      containers:
      - name: phpdemo
        image: pulsemanchaotix/phpdemo
        ports:
        - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: web-service
  ports:
  - name: http
    port: 8088
    targetPort: 8088
    protocol: TCP