apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  labels:
    app: vault
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-vault
  template:
    metadata:
      labels:
        app: app-vault
    spec:
      containers:
      - name: vault
        image: hashicorp/vault
        ports:
        - containerPort: 8200
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: 789Trocar
#        volumeMounts:
#        - mountPath: /vault/config
#       name: vault-config-dir

#  volumes:
#  - name: vault-config-dir
#    hostPath:
#      path: ./config
#      type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: my-vault
spec:
  type: LoadBalancer
  selector:
    app: app-vault
  ports:
  - name: http
    port: 8200
    targetPort: 8200